#Server connection
SERVER_IP=localhost
PASSWD=YOUR_RCON_PASSWORD
MCRCON_HOME=~/Minecraft/mcrcon

#Spawn and Worldborder
SPAWN_X=7
SPAWN_Z=12
WORLDBORDER_START=1500
WORLDBORDER_END=100

#Timings & Events
INTRO_LENGTH_MIN=1
FIRST_EPISODE=1
EPISODE_LENGTH_MIN=20
NUMBER_OF_EPISODES=10
SHRINK_AT_EPISODE=5
NOON_AT_EPISODE=9

#Just for debugging
SECS_PER_MIN=60
EFFECT_WAIT=30