#!/bin/sh
export SERVER_IP=localhost
export PASSWD=YOUR_RCON_PASSWORD
export SPAWN_X=0
#make sure you don't spawn in a wall or in the air
export SPAWN_Y=65 
export SPAWN_Z=0
#Install mcrcon from https://sourceforge.net/projects/mcrcon/
export MCRCON_HOME=~/Minecraft/mcrcon
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "gamerule sendCommandFeedback false"
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "scoreboard teams add blue" "scoreboard teams option blue color blue" "scoreboard teams empty blue" "scoreboard teams option blue friendlyfire true" "scoreboard teams option blue nametagVisibility hideForOwnTeam" "scoreboard teams option blue collisionRule always"
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "scoreboard teams add gold" "scoreboard teams option gold color gold" "scoreboard teams empty gold" "scoreboard teams option gold friendlyfire true" "scoreboard teams option gold nametagVisibility hideForOwnTeam" "scoreboard teams option gold collisionRule always"
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "scoreboard teams add green" "scoreboard teams option green color green" "scoreboard teams empty green" "scoreboard teams option green friendlyfire true" "scoreboard teams option green nametagVisibility hideForOwnTeam" "scoreboard teams option green collisionRule always"
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "scoreboard teams add aqua" "scoreboard teams option aqua color aqua" "scoreboard teams empty aqua" "scoreboard teams option aqua friendlyfire true" "scoreboard teams option aqua nametagVisibility hideForOwnTeam" "scoreboard teams option aqua collisionRule always"
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "scoreboard teams add red" "scoreboard teams option red color red" "scoreboard teams empty red" "scoreboard teams option red friendlyfire true" "scoreboard teams option red nametagVisibility hideForOwnTeam" "scoreboard teams option red collisionRule always"
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "scoreboard teams add yellow" "scoreboard teams option yellow color yellow" "scoreboard teams empty yellow" "scoreboard teams option yellow friendlyfire true" "scoreboard teams option yellow nametagVisibility hideForOwnTeam" "scoreboard teams option yellow collisionRule always"
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "scoreboard teams add purple" "scoreboard teams option purple color light_purple" "scoreboard teams empty purple" "scoreboard teams option purple friendlyfire true" "scoreboard teams option purple nametagVisibility hideForOwnTeam" "scoreboard teams option purple collisionRule always"
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "scoreboard teams add dark_blue" "scoreboard teams option dark_blue color dark_blue" "scoreboard teams empty dark_blue" "scoreboard teams option dark_blue friendlyfire true" "scoreboard teams option dark_blue nametagVisibility hideForOwnTeam" "scoreboard teams option dark_blue collisionRule always" 
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "scoreboard objectives add herzen health" "scoreboard objectives setdisplay list herzen" "effect @a minecraft:instant_health"
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "setworldspawn $SPAWN_X $SPAWN_Y $SPAWN_Z" "clear @a" "give @a minecraft:potato 20" "gamemode 0 @a" "gamerule doDaylightCycle false" "time set 6000" "tp @a $SPAWN_X $SPAWN_Y $SPAWN_Z"
$MCRCON_HOME/mcrcon -H $SERVER_IP -p $PASSWD "tellraw @a [{\"text\":\"Team beitreten: \"}, {\"text\":\"blue \", \"color\":\"blue\", \"clickEvent\": { \"action\":\"run_command\", \"value\":\"/scoreboard teams join blue\"} }, {\"text\":\"gold \", \"color\":\"gold\", \"clickEvent\": { \"action\":\"run_command\", \"value\":\"/scoreboard teams join gold\"}}, {\"text\":\"green \", \"color\":\"green\", \"clickEvent\": { \"action\":\"run_command\", \"value\":\"/scoreboard teams join green\"}}, {\"text\":\"aqua \", \"color\":\"aqua\", \"clickEvent\": { \"action\":\"run_command\", \"value\":\"/scoreboard teams join aqua\"}}, {\"text\":\"red \", \"color\":\"red\", \"clickEvent\": { \"action\":\"run_command\", \"value\":\"/scoreboard teams join red\"}}, {\"text\":\"yellow \", \"color\":\"yellow\", \"clickEvent\": { \"action\":\"run_command\", \"value\":\"/scoreboard teams join yellow\"}}, {\"text\":\"purple \", \"color\":\"light_purple\", \"clickEvent\": { \"action\":\"run_command\", \"value\":\"/scoreboard teams join purple\"}}, {\"text\":\"dark_blue \", \"color\":\"dark_blue\", \"clickEvent\": { \"action\":\"run_command\", \"value\":\"/scoreboard teams join dark_blue\"}}]"